### ISSUE TITLE
Usage from command Line?

### ISSUE THREAD

**Issue by spyda90** [RekerLab/DeltaClassifier#1]
Hi,

I am trying DeltaClassifier since we have several data pIC50<4 that we cannot used in traditional Chemprop.

However, I am wondering how to lunch a DeltaClassifier job. Is there the possibility to use command line?

Otherwise, how should I modify the .py files to run my own calculation?

My aim is to run Chemprop as I did in the past, but including this time the "<4.0" values.

Thank you in advance!

**Comment by zacharyfralish** [comment]
Thanks for your interest in the project and reaching out about this. It is nice to use the command line and we did this using shell scripts. We have added example python scripts and shell scripts to the GitHub under a new folder called ‘Command_Line_Implementation’ .

For running cross-validation.py as is, we made an example shell script for this and called it ‘cross_validations_standard.sh’. To call this from the command line in Linux, you would want to go to the directory containing the python file, shell script, and datasets of interests and then type ‘bash cross_validations_standard.sh’. To call different datasets instead of ours in the python script, you would want to replace the names of the datasets called in the python file. 

Additionally, we made a script such that you can designate what datasets to use outside of the python script by using argparse called ‘cross_validations_argparse.sh’. In cross_validations_argparse.py, we coded it such that the python file knows this argument is the input file by using either “-i” or “--input_file”. To call this from the command line in Linux, you would type ‘bash [shellscript.sh] -i [dataset.csv]’  for example ‘bash cross_validations_ argparse.sh -i CHEMBL1075138-Curated.csv’. 

Additionally, if you are using SLURM, you can designate a directory and an array of datasets to run. We made an example shell script for calling the datasets we used called ‘cross_validations_array.sh’. In this one, we indicate the directory where the files are, move to that directory, and then call the python file using datasets that end in ‘-Curated.csv’. To call this from the command line in Linux, you would type ‘bash [shellscript.sh] [pythonscript.py] [directory]’ for example ‘bash cross_validations_array.sh cross_validations_array.py home/user/chemprop’. 

Hopefully, this helps!

**Comment by spyda90** [comment]
Definitely it will help! I'll try that asap.
I will let you know if something does not work or if I have some doubts.

In the meanwhile...Thank you!

**Comment by spyda90** [comment]
Hi,

I ran the script and everything works fine till the end. Thank you.

I have a couple of more general questions.
At the end of the calculation, I obtained only CSV file with the metrics and comparisons. I was expecting to obtained a trained model(s) to be used for subsequent prediction.

I used Chemprop a lot (regression). I was hoping that using DeltaClassifier will be an alternative (better?) way to train model for prediction including also bounded values.

Can you please comments on that?

Thank you!

**Comment by zacharyfralish** [comment]
Thanks for checking back in on this. The cross validation script does just do cross validation and not subsequent prediction. To be able to make predictions on external test sets, I added another python file called 'external_test.py' and a shell script called 'external_test.sh' to call that file. What this script does is it fits the Chemprop model on the entire training dataset using the DeltaClassifier approach and then it predicts on an external test set (that must be pairs of molecules). Within the script, you can specify the training and testing data names.
I would like to clarify that DeltaClassifier is a preprocessing approaching that allows for the use of bounded datapoints, but in doing so it now predicts a classification task (is molecule A 'better' or 'worse' than molecule B) instead of a regression task. This is not a replacement for regression-based Chemprop that can also incorporate bounded data, it instead is a pre-processing approach that can be applied to any classification model (including Chemprop) that allows them to use bounded data to compare molecules. 
Hopefully this helps!

**Comment by spyda90** [comment]
Hi,

Thank you again!
I am trying to run the script but I receive the follwoing errors:

"Validating SMILES
[11:16:59] SMILES Parse Error: syntax error while parsing: =
[11:16:59] SMILES Parse Error: Failed parsing SMILES '=' for input: '='
[11:16:59] SMILES Parse Error: syntax error while parsing: <
[11:16:59] SMILES Parse Error: Failed parsing SMILES '<' for input: '<'
Test size = 0
Elapsed time = 0:00:00
Traceback (most recent call last):
  File "external_test.py", line 40, in <module>
    df_pred['Pred_Y'] = model.predict(df) # Make predictions      
  File "/share/apps/DeltaClassifier/Command_Line_Implementation/models.py", line 287, in predict
    predictions = pd.read_csv(temp_predfile.name)['Y']
  File "/share/apps/miniforge3/envs/deltaclassifier/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/share/apps/miniforge3/envs/deltaclassifier/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/share/apps/miniforge3/envs/deltaclassifier/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/share/apps/miniforge3/envs/deltaclassifier/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1679, in _make_engine
    return mapping[engine](f, **self.options)
  File "/share/apps/miniforge3/envs/deltaclassifier/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 557, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file"

My external dataset CSV file s composed by two columns. The headers are both set to "SMILES". In the first column I put the reference cpd in all the rows. In the second column I put the smile of the testing cpds I'd like to test if they are predicted better ("1") or worse ("0").

How the external dataset should be formatted? 

Thank you!

**Comment by zacharyfralish** [comment]
I have updated the python script so it should now work for your external dataset.

**Comment by spyda90** [comment]
Hi,

It seems it works fine now!
So, if I understood well, considering the reference compound in all row, first column, and the test cpds (unknown activities) in the second column:
- 0 means the test cpd is predicted to have worse activity than the reference cpd
- 1 means the test cpd is predicted to have better activity than the reference cpd

Right?

Thank you again.

**Comment by zacharyfralish** [comment]
Great, I am glad it is working for you. 

Yes, a 0 indicates the test molecule is predicted to have a lower values while a 1 indicates it predicts the test molecule to have a higher value.

**Comment by spyda90** [comment]
Thank you!
